In [1]:
import torch

# model = models_mae.MaskedAutoencoderViT()
checkpoint = torch.load('./mae_pretrain_vit_base.pth', map_location='cpu')

# checkpoint_model = checkpoint['model']
# state_dict = model.state_dict()

# msg = model.load_state_dict(checkpoint_model, strict=False)
# print(state_dict)
checkpoint

{'model': OrderedDict([('cls_token',
               tensor([[[ 2.3868e-03, -2.0984e-02, -1.0336e-02, -2.5423e-04, -4.3129e-03,
                         -4.1076e-03, -2.8852e-02, -7.7923e-02,  5.9970e-03, -6.3180e-03,
                         -1.5825e-02, -2.9038e-02, -6.7815e-02, -1.9247e-02, -2.9983e-03,
                         -4.7372e-02, -1.7901e-02, -8.1112e-04,  4.7899e-03, -9.6609e-03,
                          1.3322e-02, -3.2342e-03,  9.6007e-03, -9.4899e-03, -4.4659e-02,
                         -8.7222e-03, -2.6151e-02, -1.1055e-02, -4.2712e-03, -3.9098e-03,
                         -1.2414e-02, -2.1145e-03, -4.3700e-02, -6.2158e-03, -1.2625e-02,
                         -1.1006e-02, -2.1523e-02, -2.5771e-03,  8.1681e-04, -2.0704e-02,
                         -4.0477e-03,  3.7824e-03,  1.1361e-02, -8.6010e-03, -5.3792e-03,
                         -2.0909e-03, -7.8730e-03, -3.8817e-03, -8.0425e-03, -1.7786e-02,
                          1.1115e-02,  1.0345e-03,  2.4080e-03,

In [2]:
checkpoint['model']

OrderedDict([('cls_token',
              tensor([[[ 2.3868e-03, -2.0984e-02, -1.0336e-02, -2.5423e-04, -4.3129e-03,
                        -4.1076e-03, -2.8852e-02, -7.7923e-02,  5.9970e-03, -6.3180e-03,
                        -1.5825e-02, -2.9038e-02, -6.7815e-02, -1.9247e-02, -2.9983e-03,
                        -4.7372e-02, -1.7901e-02, -8.1112e-04,  4.7899e-03, -9.6609e-03,
                         1.3322e-02, -3.2342e-03,  9.6007e-03, -9.4899e-03, -4.4659e-02,
                        -8.7222e-03, -2.6151e-02, -1.1055e-02, -4.2712e-03, -3.9098e-03,
                        -1.2414e-02, -2.1145e-03, -4.3700e-02, -6.2158e-03, -1.2625e-02,
                        -1.1006e-02, -2.1523e-02, -2.5771e-03,  8.1681e-04, -2.0704e-02,
                        -4.0477e-03,  3.7824e-03,  1.1361e-02, -8.6010e-03, -5.3792e-03,
                        -2.0909e-03, -7.8730e-03, -3.8817e-03, -8.0425e-03, -1.7786e-02,
                         1.1115e-02,  1.0345e-03,  2.4080e-03, -4.9258e-03, -1.2319

In [12]:
state_dict = checkpoint['model']
for i, data in enumerate(state_dict):
    print(data)
    print(type(state_dict[data]))
    print("shape:",state_dict[data].data.size())
    print("grad:",state_dict[data].requires_grad)
    # break

cls_token
<class 'torch.Tensor'>
shape: torch.Size([1, 1, 768])
grad: False
pos_embed
<class 'torch.Tensor'>
shape: torch.Size([1, 197, 768])
grad: False
patch_embed.proj.weight
<class 'torch.Tensor'>
shape: torch.Size([768, 3, 16, 16])
grad: False
patch_embed.proj.bias
<class 'torch.Tensor'>
shape: torch.Size([768])
grad: False
blocks.0.norm1.weight
<class 'torch.Tensor'>
shape: torch.Size([768])
grad: False
blocks.0.norm1.bias
<class 'torch.Tensor'>
shape: torch.Size([768])
grad: False
blocks.0.attn.qkv.weight
<class 'torch.Tensor'>
shape: torch.Size([2304, 768])
grad: False
blocks.0.attn.proj.weight
<class 'torch.Tensor'>
shape: torch.Size([768, 768])
grad: False
blocks.0.attn.proj.bias
<class 'torch.Tensor'>
shape: torch.Size([768])
grad: False
blocks.0.norm2.weight
<class 'torch.Tensor'>
shape: torch.Size([768])
grad: False
blocks.0.norm2.bias
<class 'torch.Tensor'>
shape: torch.Size([768])
grad: False
blocks.0.mlp.fc1.weight
<class 'torch.Tensor'>
shape: torch.Size([3072, 768])
g

In [10]:
len(state_dict)

cls_token
tensor([[[ 2.3868e-03, -2.0984e-02, -1.0336e-02, -2.5423e-04, -4.3129e-03,
          -4.1076e-03, -2.8852e-02, -7.7923e-02,  5.9970e-03, -6.3180e-03,
          -1.5825e-02, -2.9038e-02, -6.7815e-02, -1.9247e-02, -2.9983e-03,
          -4.7372e-02, -1.7901e-02, -8.1112e-04,  4.7899e-03, -9.6609e-03,
           1.3322e-02, -3.2342e-03,  9.6007e-03, -9.4899e-03, -4.4659e-02,
          -8.7222e-03, -2.6151e-02, -1.1055e-02, -4.2712e-03, -3.9098e-03,
          -1.2414e-02, -2.1145e-03, -4.3700e-02, -6.2158e-03, -1.2625e-02,
          -1.1006e-02, -2.1523e-02, -2.5771e-03,  8.1681e-04, -2.0704e-02,
          -4.0477e-03,  3.7824e-03,  1.1361e-02, -8.6010e-03, -5.3792e-03,
          -2.0909e-03, -7.8730e-03, -3.8817e-03, -8.0425e-03, -1.7786e-02,
           1.1115e-02,  1.0345e-03,  2.4080e-03, -4.9258e-03, -1.2319e-02,
          -2.0058e-02,  1.7224e-03, -3.5470e-03, -3.7536e-03, -1.9259e-02,
          -5.0482e-03, -6.0937e-03, -4.2860e-03, -4.7415e-01, -5.3420e-03,
          -3.47

150

In [5]:
import models_mae
from functools import partial
from torch import nn
# net = models_mae.MaskedAutoencoderViT(
#         patch_size=16, embed_dim=768, depth=12, num_heads=12,
#         decoder_embed_dim=512, decoder_depth=8, decoder_num_heads=16,
#         mlp_ratio=4, norm_layer=partial(nn.LayerNorm, eps=1e-6))
net = models_mae.mae_vit_base_patch16_dec512d8b()
net

MaskedAutoencoderViT(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (blocks): ModuleList(
    (0-11): 12 x Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
  )
  (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=T

In [8]:
# net.load_state_dict(checkpoint['model'], strict=False)
count = 0
for name, parms in net.named_parameters():	
    print('-->name:', name)
    # print('-->grad_requirs:',parms.requires_grad)
    # print('-->grad_value:',parms.grad)
    # print("======================================")

-->name: cls_token
-->name: pos_embed
-->name: mask_token
-->name: decoder_pos_embed
-->name: patch_embed.proj.weight
-->name: patch_embed.proj.bias
-->name: blocks.0.norm1.weight
-->name: blocks.0.norm1.bias
-->name: blocks.0.attn.qkv.weight
-->name: blocks.0.attn.qkv.bias
-->name: blocks.0.attn.proj.weight
-->name: blocks.0.attn.proj.bias
-->name: blocks.0.norm2.weight
-->name: blocks.0.norm2.bias
-->name: blocks.0.mlp.fc1.weight
-->name: blocks.0.mlp.fc1.bias
-->name: blocks.0.mlp.fc2.weight
-->name: blocks.0.mlp.fc2.bias
-->name: blocks.1.norm1.weight
-->name: blocks.1.norm1.bias
-->name: blocks.1.attn.qkv.weight
-->name: blocks.1.attn.qkv.bias
-->name: blocks.1.attn.proj.weight
-->name: blocks.1.attn.proj.bias
-->name: blocks.1.norm2.weight
-->name: blocks.1.norm2.bias
-->name: blocks.1.mlp.fc1.weight
-->name: blocks.1.mlp.fc1.bias
-->name: blocks.1.mlp.fc2.weight
-->name: blocks.1.mlp.fc2.bias
-->name: blocks.2.norm1.weight
-->name: blocks.2.norm1.bias
-->name: blocks.2.attn.qkv.

In [7]:
len(net.state_dict())

254

In [15]:
net_dict = net.state_dict()

new_state_dict = {k:v for k,v in state_dict.items() if k in state_dict.keys()}
len(new_state_dict.keys())

150

In [20]:
net_dict.update(new_state_dict)
net.load_state_dict(net_dict)

<All keys matched successfully>

In [4]:
import models_mae
models_mae.__dict__['mae_vit_base_patch16']()

MaskedAutoencoderViT(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (blocks): ModuleList(
    (0-11): 12 x Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
  )
  (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=T

In [ ]:
net.train()
for name, parms in net.named_parameters():	
    print('-->name:', name)
    print('-->grad_requirs:',parms.requires_grad)
    # print('-->grad_value:',parms.grad)
    print("======================================")