In [1]:
import torch

# model = models_mae.MaskedAutoencoderViT()
# checkpoint = torch.load('./mae_pretrain_vit_base.pth', map_location='cpu')
checkpoint = torch.load('./mae_visualize_vit_large_ganloss.pth', map_location='cpu')

# checkpoint_model = checkpoint['model']
# state_dict = model.state_dict()

# msg = model.load_state_dict(checkpoint_model, strict=False)
# print(state_dict)
checkpoint

{'model': OrderedDict([('cls_token',
               tensor([[[-0.0559, -0.0216, -0.0273,  ..., -0.0121, -0.0132,  0.0050]]])),
              ('pos_embed',
               tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                        [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
                        [ 0.8415,  0.8219,  0.8020,  ...,  1.0000,  1.0000,  1.0000],
                        ...,
                        [-1.0000, -0.9271, -0.7253,  ...,  1.0000,  1.0000,  1.0000],
                        [-0.5366, -0.8363, -0.9854,  ...,  1.0000,  1.0000,  1.0000],
                        [ 0.4202, -0.0258, -0.4519,  ...,  1.0000,  1.0000,  1.0000]]])),
              ('mask_token',
               tensor([[[ 1.4541e-01,  1.2273e-01,  9.0448e-02,  7.0783e-02,  4.0660e-02,
                          5.8495e-02,  1.7817e-03,  5.2666e-02,  5.6388e-02,  7.3805e-02,
                          3.7450e-02, -2.8224e-03,  6.2193e-02,  6.4187e-02,  1.5591e-0

In [2]:
checkpoint['model']

OrderedDict([('cls_token',
              tensor([[[-0.0559, -0.0216, -0.0273,  ..., -0.0121, -0.0132,  0.0050]]])),
             ('pos_embed',
              tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                       [ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
                       [ 0.8415,  0.8219,  0.8020,  ...,  1.0000,  1.0000,  1.0000],
                       ...,
                       [-1.0000, -0.9271, -0.7253,  ...,  1.0000,  1.0000,  1.0000],
                       [-0.5366, -0.8363, -0.9854,  ...,  1.0000,  1.0000,  1.0000],
                       [ 0.4202, -0.0258, -0.4519,  ...,  1.0000,  1.0000,  1.0000]]])),
             ('mask_token',
              tensor([[[ 1.4541e-01,  1.2273e-01,  9.0448e-02,  7.0783e-02,  4.0660e-02,
                         5.8495e-02,  1.7817e-03,  5.2666e-02,  5.6388e-02,  7.3805e-02,
                         3.7450e-02, -2.8224e-03,  6.2193e-02,  6.4187e-02,  1.5591e-02,
                    

In [3]:
state_dict = checkpoint['model']
for i, data in enumerate(state_dict):
    print(data)
    print(type(state_dict[data]))
    print("shape:",state_dict[data].data.size())
    print("grad:",state_dict[data].requires_grad)
    # break

cls_token
<class 'torch.Tensor'>
shape: torch.Size([1, 1, 1024])
grad: False
pos_embed
<class 'torch.Tensor'>
shape: torch.Size([1, 197, 1024])
grad: False
mask_token
<class 'torch.Tensor'>
shape: torch.Size([1, 1, 512])
grad: False
decoder_pos_embed
<class 'torch.Tensor'>
shape: torch.Size([1, 197, 512])
grad: False
patch_embed.proj.weight
<class 'torch.Tensor'>
shape: torch.Size([1024, 3, 16, 16])
grad: False
patch_embed.proj.bias
<class 'torch.Tensor'>
shape: torch.Size([1024])
grad: False
blocks.0.norm1.weight
<class 'torch.Tensor'>
shape: torch.Size([1024])
grad: False
blocks.0.norm1.bias
<class 'torch.Tensor'>
shape: torch.Size([1024])
grad: False
blocks.0.attn.qkv.weight
<class 'torch.Tensor'>
shape: torch.Size([3072, 1024])
grad: False
blocks.0.attn.qkv.bias
<class 'torch.Tensor'>
shape: torch.Size([3072])
grad: False
blocks.0.attn.proj.weight
<class 'torch.Tensor'>
shape: torch.Size([1024, 1024])
grad: False
blocks.0.attn.proj.bias
<class 'torch.Tensor'>
shape: torch.Size([102

In [4]:
len(state_dict)

398

In [5]:
import models_mae
from functools import partial
from torch import nn
# net = models_mae.MaskedAutoencoderViT(
#         patch_size=16, embed_dim=768, depth=12, num_heads=12,
#         decoder_embed_dim=512, decoder_depth=8, decoder_num_heads=16,
#         mlp_ratio=4, norm_layer=partial(nn.LayerNorm, eps=1e-6))
# net = models_mae.mae_vit_base_patch16_dec512d8b()
net = models_mae.mae_vit_large_patch16_dec512d8b()
net

MaskedAutoencoderViT(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 1024, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (blocks): ModuleList(
    (0-23): 24 x Block(
      (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=1024, out_features=3072, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=1024, out_features=1024, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=1024, out_features=4096, bias=True)
        (act): GELU(approximate='none')
        (fc2): Linear(in_features=4096, out_features=1024, bias=True)
        (drop): Dropout(p=0.0, inplace=False)
      )
    )
  )
  (norm): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
  (decoder_embed): Linear(in_featu

In [6]:
# net.load_state_dict(checkpoint['model'], strict=False)
count = 0
for name, parms in net.named_parameters():	
    print('-->name:', name)
    # print('-->grad_requirs:',parms.requires_grad)
    # print('-->grad_value:',parms.grad)
    # print("======================================")

-->name: cls_token
-->name: pos_embed
-->name: mask_token
-->name: decoder_pos_embed
-->name: patch_embed.proj.weight
-->name: patch_embed.proj.bias
-->name: blocks.0.norm1.weight
-->name: blocks.0.norm1.bias
-->name: blocks.0.attn.qkv.weight
-->name: blocks.0.attn.qkv.bias
-->name: blocks.0.attn.proj.weight
-->name: blocks.0.attn.proj.bias
-->name: blocks.0.norm2.weight
-->name: blocks.0.norm2.bias
-->name: blocks.0.mlp.fc1.weight
-->name: blocks.0.mlp.fc1.bias
-->name: blocks.0.mlp.fc2.weight
-->name: blocks.0.mlp.fc2.bias
-->name: blocks.1.norm1.weight
-->name: blocks.1.norm1.bias
-->name: blocks.1.attn.qkv.weight
-->name: blocks.1.attn.qkv.bias
-->name: blocks.1.attn.proj.weight
-->name: blocks.1.attn.proj.bias
-->name: blocks.1.norm2.weight
-->name: blocks.1.norm2.bias
-->name: blocks.1.mlp.fc1.weight
-->name: blocks.1.mlp.fc1.bias
-->name: blocks.1.mlp.fc2.weight
-->name: blocks.1.mlp.fc2.bias
-->name: blocks.2.norm1.weight
-->name: blocks.2.norm1.bias
-->name: blocks.2.attn.qkv.

In [7]:
len(net.state_dict())

398

In [8]:
net_dict = net.state_dict()

new_state_dict = {k:v for k,v in state_dict.items() if k in state_dict.keys()}
len(new_state_dict.keys())

398

In [9]:
net_dict.update(new_state_dict)
net.load_state_dict(net_dict)

<All keys matched successfully>

In [4]:
import models_mae
models_mae.__dict__['mae_vit_base_patch16']()

MaskedAutoencoderViT(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 768, kernel_size=(16, 16), stride=(16, 16))
    (norm): Identity()
  )
  (blocks): ModuleList(
    (0-11): 12 x Block(
      (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (attn): Attention(
        (qkv): Linear(in_features=768, out_features=2304, bias=True)
        (attn_drop): Dropout(p=0.0, inplace=False)
        (proj): Linear(in_features=768, out_features=768, bias=True)
        (proj_drop): Dropout(p=0.0, inplace=False)
      )
      (drop_path): Identity()
      (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
      (mlp): Mlp(
        (fc1): Linear(in_features=768, out_features=3072, bias=True)
        (act): GELU(approximate='none')
        (drop1): Dropout(p=0.0, inplace=False)
        (fc2): Linear(in_features=3072, out_features=768, bias=True)
        (drop2): Dropout(p=0.0, inplace=False)
      )
    )
  )
  (norm): LayerNorm((768,), eps=1e-06, elementwise_affine=T

In [10]:
net.train()
for name, parms in net.named_parameters():	
    print('-->name:', name)
    print('-->grad_requirs:',parms.requires_grad)
    # print('-->grad_value:',parms.grad)
    print("======================================")

-->name: cls_token
-->grad_requirs: True
-->name: pos_embed
-->grad_requirs: False
-->name: mask_token
-->grad_requirs: True
-->name: decoder_pos_embed
-->grad_requirs: False
-->name: patch_embed.proj.weight
-->grad_requirs: True
-->name: patch_embed.proj.bias
-->grad_requirs: True
-->name: blocks.0.norm1.weight
-->grad_requirs: True
-->name: blocks.0.norm1.bias
-->grad_requirs: True
-->name: blocks.0.attn.qkv.weight
-->grad_requirs: True
-->name: blocks.0.attn.qkv.bias
-->grad_requirs: True
-->name: blocks.0.attn.proj.weight
-->grad_requirs: True
-->name: blocks.0.attn.proj.bias
-->grad_requirs: True
-->name: blocks.0.norm2.weight
-->grad_requirs: True
-->name: blocks.0.norm2.bias
-->grad_requirs: True
-->name: blocks.0.mlp.fc1.weight
-->grad_requirs: True
-->name: blocks.0.mlp.fc1.bias
-->grad_requirs: True
-->name: blocks.0.mlp.fc2.weight
-->grad_requirs: True
-->name: blocks.0.mlp.fc2.bias
-->grad_requirs: True
-->name: blocks.1.norm1.weight
-->grad_requirs: True
-->name: blocks.1.